ameblo:
  regular_crawl:
    - ID: 'ogurayui-0815'
      member_id: 2
    - ID: 'ishiharakaori-0806'
      member_id: 3
  stopped_updating:
    - ID: 'ogura-yui'
      member_id: 2
    - ID: 'ishiharakaori'
      member_id: 3

instagram:
  username: 'jas_yuikaori'
  password: 'darkarmed'
  regular_crawl:
    - ID: 'yui_ogura_official'
      member_id: 2

twitter:
  consumer_key: 'HICQLnFdWvpD390L7hw6Y3Phx'
  consumer_secret: 'x02WyH82h76ETJlpWvFu7R9Nhhfgty6TuMBKp1ZXaENRNPx2Qc'
  access_token: '272968442-MnbnHokfqR9lyWS8pNm2JzhG426osPb777LYPDqm'
  access_token_secret: 'MsVaeBYwqzP0uWiNyiBwnrxTTFQYwPThuqik8EzdtmHR0'
  regular_crawl:
    - ID: 'yuikaori_staff'
      member_id: 1

official_site:
  regular_crawl:
    - host: 'www.yuikaori.info'
      member_id: 1
      accept: ''
    - host: 'www.ogurayui.jp'
      member_id: 2
      accept: ''
    - host: 'yuikaori-report.info'
      member_id: 1
      accept: ''

news_site:
  - 'natalie.mu/music/news'
  - 'natalie.mu/music/pp'
  - 'www.animatetimes.com/news'
  - 'top.tsite.jp/news'
  - 'www.barks.jp/news'

extname:
  images:
    - '.jpg'
    - '.png'
    - '.jpeg'
  videos:
    - '.mp4'

media:
  root: 'https://s3-us-west-2.amazonaws.com/yuikaori-herokuapp-com/images/'
