ameblo:
  regular_crawl:
    - ID: 'ogurayui-0815'
      member_id: 2
    - ID: 'ishiharakaori-0806'
      member_id: 3
  stopped_updating:
    - ID: 'ogura-yui'
      member_id: 2
    - ID: 'ishiharakaori'
      member_id: 3

instagram:
  username: 'jas_yuikaori'
  password: 'darkarmed'
  regular_crawl:
    - ID: 'yui_ogura_official'
      member_id: 2

twitter:
  regular_crawl:
    - ID: 'yuikaori_staff'
      member_id: 1

official_site:
  regular_crawl:
    - url: 'http://www.yuikaori.info/'
      host: 'www.yuikaori.info'
      member_id: 1
      allowed: []
    - url: 'http://www.ogurayui.jp/'
      host: 'www.ogurayui.jp'
      member_id: 2
      allowed: []
    - url: 'http://yuikaori-report.info/'
      host: 'yuikaori-report.info'
      member_id: 1
      allowed: []

news_site:
  - 'natalie.mu/music/news'
  - 'natalie.mu/music/pp'
  - 'www.animatetimes.com/news'
  - 'top.tsite.jp/news'
  - 'www.barks.jp/news'

extname:
  images:
    - '.jpg'
    - '.png'
    - '.jpeg'
  videos:
    - '.mp4'

media:
  root: 'https://s3-us-west-2.amazonaws.com/yuikaori-herokuapp-com/'
